apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: pod1
      labels:
        app: myapp
    spec:
      containers:
        - name: container1
          image: httpd
          ports:
            - containerPort: 3000
